name: cicd

on:
  push:
    branches:
      - main
permissions:
  actions: write
jobs:

  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
      
      - name: Git Version
        id: versionning
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main
          dev-branch: dev
          log-paths: Kexa/
          minor-identifier: 'feat:'
          major-identifier: 'break:'
      
      - name: Set up version in file
        run: echo "${{ steps.versionning.outputs.version }}" > VERSION

      - name: update version in code
        run: npm run update

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      #- name: List all changed files
      #  run: |
      #    echo "## ${{ steps.versionning.outputs.version }}" >> CHANGELOG.md
      #    echo "### Files added: ${{steps.changed-files.outputs.added_files_count}}" >> CHANGELOG.md
      #    echo "" >> CHANGELOG.md
      #    for file in ${{ steps.changed-files.outputs.added_files }}; do 
      #      echo "$file was added" >> CHANGELOG.md
      #      echo "" >> CHANGELOG.md
      #    done
      #    echo "### Files changed: ${{steps.changed-files.outputs.all_changed_and_modified_files_count}}" >> CHANGELOG.md
      #    echo "" >> CHANGELOG.md
      #    for file in ${{ steps.changed-files.outputs.all_changed_files }}; do 
      #      echo "$file was changed" >> CHANGELOG.md
      #      echo "" >> CHANGELOG.md
      #    done
      #    echo "" >> CHANGELOG.md
      
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: estebanmathia
          author_email: esteban.mathia@supinfo.com
          force: false
          signoff: false
          message: 'add info extract from addon'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.versionning.outputs.version }}"

      #- name: Extraction du YAML secret
      #  run: echo "${{ secrets.YAML_CONFIG_KUBE }}" > config/kubernetes.yaml

      #- name: Kexa
      #  id: kexa
      #  uses: ./
      #  with:
      #    DEBUG_MODE: DEBUG
      #    EMAILPWD: ${{ secrets.PWD_EMAIL }} 
      #    EMAILFROM: "'ISEE' <ateliertechniquededev@gmail.com>"
      #    #EMAILPORT: 587
      #    #EMAILUSER: "apikey"
      #    #EMAILHOST: "smtp.sendgrid.net"
      #    DEMO-GITHUBTOKEN: ${{ secrets.TOKEN_KEXA_GITHUB }}
      #    DEMO-KUBECONFIG: "./config/kubernetes.yaml"
      #    TEST: "tout est ok"